name: untitled
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_intl: ^0.0.1
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.1
  flutter_dotenv: ^5.0.2
  autocomplete_textfield: ^2.0.1
  get: ^4.1.4
  flutter_slidable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/.env
    - assets/themes.json
    - assets/cities.json
    - assets/images/img0.jpg
    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
    - assets/images/img4.jpg
    - assets/images/img5.jpg
    - assets/images/img6.jpg
    - assets/images/car0.jpg
    - assets/images/car1.jpg
    - assets/images/car2.jpg
    - assets/images/car3.jpg
    - assets/images/car4.jpg
    - assets/images/car5.jpg
    - assets/images/car6.jpg
    - assets/images/car7.jpg
    - assets/images/car8.jpg
    - assets/images/car9.jpg
    - assets/images/car10.jpg
    - assets/images/weather_icons/view0.jpg
    - assets/images/weather_icons/view1.jpg
    - assets/images/weather_icons/theme0.jpg
    - assets/images/weather_icons/theme1.jpg
    - assets/images/weather_icons/theme2.jpg
    - assets/images/weather_icons/theme3.jpg
