name: untitled
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_intl: ^0.0.1
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.1
  flutter_dotenv: ^5.0.2
  autocomplete_textfield: ^2.0.1
  get: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/.env
    - assets/themes.json
    - assets/cities.json
