name: untitled
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_intl: ^0.0.1
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.1
  flutter_dotenv: ^5.0.2
  autocomplete_textfield: ^2.0.1
  get: ^4.1.4
  flutter_slidable: ^1.2.0
  speech_to_text: ^6.1.1
  flutter_spinkit: ^5.1.0
  flutter_beautiful_popup: ^1.5.0
  flutter_animated_dialog: ^2.0.1
  flutter_animate: ^4.2.0
  carousel_slider: ^4.2.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  dots_indicator: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/.env
    - assets/themes.json
    - assets/cities.json

    - assets/images/background_imgs/img0.jpg
    - assets/images/background_imgs/img1.jpg
    - assets/images/background_imgs/img2.jpg
    - assets/images/background_imgs/img3.jpg
    - assets/images/background_imgs/img4.jpg
    - assets/images/background_imgs/img5.jpg
    - assets/images/background_imgs/img6.jpg
    - assets/images/background_imgs/img7.jpg
    - assets/images/background_imgs/img8.jpg
    - assets/images/background_imgs/img9.jpg
    - assets/images/background_imgs/img10.jpg
    - assets/images/background_imgs/img11.jpg
    - assets/images/background_imgs/img12.jpg
    - assets/images/background_imgs/img13.jpg
    - assets/images/background_imgs/img14.jpg
    - assets/images/background_imgs/img15.jpg
    - assets/images/background_imgs/img16.jpg
    - assets/images/background_imgs/img17.jpg
    - assets/images/background_imgs/img18.jpg
    - assets/images/background_imgs/img19.jpg
    - assets/images/background_imgs/img20.jpg
    - assets/images/background_imgs/img21.jpg
    - assets/images/background_imgs/img22.jpg
    - assets/images/background_imgs/img23.jpg
    - assets/images/background_imgs/img24.jpg
    - assets/images/background_imgs/img25.jpg
    - assets/images/background_imgs/img26.jpg

    - assets/images/icons/theme0.jpg
    - assets/images/icons/theme1.jpg
    - assets/images/icons/theme2.jpg
    - assets/images/icons/theme3.jpg
    - assets/images/icons/view0.jpg
    - assets/images/icons/view1.jpg

    - assets/images/infor.jpg

    - assets/images/weather_icons/icons0.png
    - assets/images/weather_icons/icons1.png
    - assets/images/weather_icons/icons2.png
    - assets/images/weather_icons/icons3.png
    - assets/images/weather_icons/icons4.png
    - assets/images/weather_icons/icons5.png
    - assets/images/weather_icons/icons6.png
    - assets/images/weather_icons/icons7.png
    - assets/images/weather_icons/icons8.png
    - assets/images/weather_icons/icons9.png
    - assets/images/weather_icons/icons10.png
    - assets/images/weather_icons/icons11.png
    - assets/images/weather_icons/icons12.png
    - assets/images/weather_icons/icons13.png
    - assets/images/weather_icons/icons14.png
    - assets/images/weather_icons/icons15.png
    - assets/images/weather_icons/icons16.png
    - assets/images/weather_icons/icons17.png
    - assets/images/weather_icons/icons18.png
    - assets/images/weather_icons/icons19.png
    - assets/images/weather_icons/icons20.png
    - assets/images/weather_icons/icons21.png
    - assets/images/weather_icons/icons22.png
    - assets/images/weather_icons/icons23.png
    - assets/images/weather_icons/icons24.png
    - assets/images/weather_icons/icons25.png
    - assets/images/weather_icons/icons26.png

