name: untitled
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_intl: ^0.0.1
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  provider: ^6.0.1
  flutter_dotenv: ^5.0.2
  autocomplete_textfield: ^2.0.1
  get: ^4.1.4
  flutter_slidable: ^1.2.0
  speech_to_text: ^6.1.1
  flutter_spinkit: ^5.1.0
  flutter_beautiful_popup: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/.env
    - assets/themes.json
    - assets/cities.json
    - assets/images/img0.jpg
    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
    - assets/images/img4.jpg
    - assets/images/img5.jpg
    - assets/images/img6.jpg
    - assets/images/img7.jpg
    - assets/images/img8.jpg
    - assets/images/img9.jpg
    - assets/images/img10.jpg
    - assets/images/img11.jpg
    - assets/images/img12.jpg
    - assets/images/img13.jpg
    - assets/images/img14.jpg
    - assets/images/img15.jpg
    - assets/images/img16.jpg
    - assets/images/img17.jpg
    - assets/images/img18.jpg
    - assets/images/img19.jpg
    - assets/images/img20.jpg
    - assets/images/img21.jpg
    - assets/images/img22.jpg
    - assets/images/img23.jpg
    - assets/images/img24.jpg
    - assets/images/img25.jpg
    - assets/images/img26.jpg
    - assets/images/weather_icons/theme0.jpg
    - assets/images/weather_icons/theme1.jpg
    - assets/images/weather_icons/theme2.jpg
    - assets/images/weather_icons/theme3.jpg
    - assets/images/weather_icons/view0.jpg
    - assets/images/weather_icons/view1.jpg